version: '3.3'

services:
  db:
    image: mysqlcompose
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - dockercompose
  
  backend:
    image: flaskcompose
    ports:
      - "5000:5000"
    restart: always
    networks:
      - dockercompose
    depends_on:
      - db

networks:
  dockercompose:
    driver: bridge